name = "bitmap"
version = "0.10.0"
keywords = ["graphics", "image", "bitmap", "png"]
defaultTargets = ["Bitmap"]
testDriver = "bitmap_tests"

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false
lang.lemmaCmd = true

[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "023ce7d62a0531e22a5331e20b587817a80d49ff"

[[lean_lib]]
name = "Bitmap"

[[lean_exe]]
name = "bitmap_tests"
root = "Bitmap.Tests"
