name = "bitmap"
version = "0.9.0"
keywords = ["graphics", "image", "bitmap", "png"]
defaultTargets = ["Bitmap"]
testDriver = "bitmap_tests"

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false
lang.lemmaCmd = true

[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "32dc18cde3684679f3c003de608743b57498c56f"

[[lean_lib]]
name = "Bitmap"

[[lean_exe]]
name = "bitmap_tests"
root = "Bitmap.Tests"
